---

- name: create vault system group
  group:
    name: 'vault'
    system: true

- name: create vault system user
  user:
    name: 'vault'
    system: true
    shell: '/sbin/nologin'
    group: 'vault'
    createhome: true
    home: '/var/lib/vault'

# vim: set et st=2 sts=2 sw=2 ts=2:
